### ISSUE TITLE
Panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by ftomza** [plandem/xlsx#52]
When trying to read the hidden "info" sheet, a panic occurs. I attach the file.

[bad.xlsx](https://storage.yandexcloud.net/product-import/73/82/7382d1f21a55d350.xlsx)

```console
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 50 [running]:
testing.tRunner.func1.1(0x19ea560, 0xc0003cbfa0)
	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000001e00)
	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1075 +0x41a
panic(0x19ea560, 0xc0003cbfa0)
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
github.com/plandem/xlsx.(*sheetReadWrite).expandOnInit(0xc0000103e0)
	/Users/arzaborskiy/go/pkg/mod/github.com/plandem/xlsx@v1.0.4/sheet_readwrite.go:250 +0x516
github.com/plandem/ooxml.(*PackageFile).LoadIfRequired(0xc000238910, 0xc000515c20)
	/Users/arzaborskiy/go/pkg/mod/github.com/plandem/ooxml@v1.1.2/package_file.go:93 +0x8e
github.com/plandem/xlsx.(*sheetReadWrite).afterOpen(0xc0000103e0)
	/Users/arzaborskiy/go/pkg/mod/github.com/plandem/xlsx@v1.0.4/sheet_readwrite.go:360 +0x5c
github.com/plandem/xlsx.(*Spreadsheet).Sheet(0xc0002381e0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x203000)
	/Users/arzaborskiy/go/pkg/mod/github.com/plandem/xlsx@v1.0.4/spreadsheet.go:106 +0x232
github.com/plandem/xlsx.(*Spreadsheet).SheetByName(0xc0002381e0, 0x1a6de1d, 0x4, 0x0, 0x0, 0x0, 0xc000515db8, 0x100f830)
	/Users/arzaborskiy/go/pkg/mod/github.com/plandem/xlsx@v1.0.4/spreadsheet.go:60 +0xde

```

if you open the sheet with the option `SheetModeIgnoreDimension`, then everything is ok

```go
sheet := file.SheetByName(name, xlsx.SheetModeIgnoreDimension)
```

**Comment by plandem** [comment]
It happens when sheet has wrong dimension. That's why its working with `SheetModeIgnoreDimension`, because in this case library ignores these values.
